### PR TITLE
Add raw option

### PR DESCRIPTION
**Pull request by evilive3000**

### CODE REVIEW

**Comment by parshap** [comment]
Awesome! Wondering if there's a better output format than a string of comma-delimited integers? Maybe we turn that into a buffer of the raw binary data?

**Comment by evilive3000** [comment]
Well, as for me, I need an array of integers so I do `fingerprint.split(',').map(i => parseInt(i))` and compare int-to-int with another fingerprint to calculate similarity.

**Comment by parshap** [comment]
Would having a buffer make that more difficult for you? Specifically, I'm thinking of the following change:

```diff
diff --git a/index.js b/index.js
index 87a5b28..0e24e40 100644
--- a/index.js
+++ b/index.js
@@ -31,7 +31,16 @@ module.exports = function(file, options, callback) {
        run(args, options)
                .on("error", callback)
                .pipe(parse())
-               .on("data", callback.bind(null, null));
+               .on("data", function(results) {
+                       if (options.raw) {
+                               results.fingerprint = new Buffer(
+                                       results.fingerprint.split(",").map(function(value) {
+                                               return parseInt(value);
+                                       })
+                               );
+                       }
+                       callback(null, results);
+               });
 };

 // -- Run fpcalc command
```

I feel like this may be a better interface for general use, but I'm happy to be told otherwise. What do you think?

**Comment by evilive3000** [comment]
I'm agree, it's look reasonable.

**Comment by parshap** [comment]
Excellent! Merged and made the buffer change. Published `fpcalc@1.2.0` to npm.

Thank you for the excellent PR and feedback.

**Comment by evilive3000** [comment]
Thank you for your work!

**Comment by evilive3000** [comment]
Man, we've run into a problem with `buffer`.
`Buffer` is only `Uint8Array`[*](https://nodejs.org/api/buffer.html#buffer_buffers_and_typedarray), so we lose 3 bytes each value.
    
    var buf = new Buffer([255,256]) // <Buffer ff 00>

I suggest to replace `buffer` with `Int32Array`:

    Int32Array.from(results.fingerprint.split(",").map(function(value) {
        return parseInt(value);
    }));

**Comment by parshap** [comment]
Oop! I've fixed this and release `1.2.1`. The `fingerprint` value is still a buffer. I'm also now exposing the original raw string value as `fingerprintRaw`.

**Pull request merged**
